<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <Platforms>x64</Platforms>
    <PackageId>ROC Module Lua</PackageId>
    <Version>1.0.0</Version>
    <Authors>SDraw</Authors>
    <Company></Company>
    <Product>ROC Module Lua</Product>
    <AssemblyName>roc_module_lua</AssemblyName>
    <OutputType>Library</OutputType>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <RootNamespace>ROC.Module</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>..\bin\win64\</OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="lua" Version="5.4.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\roc_app\roc_app.csproj" />
  </ItemGroup>

</Project>